### ISSUE TITLE
venv и .idea не должны быть в репозитории

### ISSUE THREAD

**Issue by ilyaevseev** [Pythoniser/Python_Telegram_Bot#1]
https://github.com/Pythoniser/Python_Telegram_Bot/blob/1f0927c8dd2bbadaa6f6ad52f59481a5f438b1d3/.gitignore#L1

PyCharm при инициализации git-репозитория в проекте генерирует большой .gitignore, который лучше не перезатирать, а дополнять.

**venv** содержит динамически генерируемое содержимое для конкретной платформы, в репозитории ему делать нечего.

**.idea** содержит ваши личные настройки, их тоже лучше не публиковать, если внутри есть пароли или ключи.

**Comment by Pythoniser** [comment]
Сделано.

**Comment by ilyaevseev** [comment]
Если сделано, то issue надо закрыть.

Гитхаб умеет автоматически закрывать issue, если сообщение в исправляющем коммите содержит её номер, например:

Fix #1: remove venv and .idea from repo

**Comment by ilyaevseev** [comment]
Fixed by a35333e27d88ce2a277f5ac79ccb1f20adee8f03
