### ISSUE TITLE
Слишком жесткая зависимость от структуры входных данных

### ISSUE THREAD

**Issue by ilyaevseev** [Pythoniser/Python_Telegram_Bot#11]
https://github.com/Pythoniser/Python_Telegram_Bot/blob/e02d7c118083bf4a7d786e95e2af50804ce53772/main.py#L20

Если банк поменяет ширину столбцов, желательно:
* как минимум - обнаруживать такую ситуацию и сообщать об ошибке
* оптимально - приспосабливаться на лету

**Comment by Pythoniser** [comment]
Можно, просто дольше через набор ключей. я сделал побыстрее. Но я думал о более надежном варианте.

**Comment by Pythoniser** [comment]
Сделано. Сгенерирован список ключей словаря со значениями адресных данных и далее через двойной цикл накидываются адреса в список адресов отделений банков с наивысшим курсом покупки USD.

**Comment by Pythoniser** [comment]
Сделано. Сгенерирован список ключей словаря со значениями адресных данных и далее через двойной цикл значения конкатенацией накидываются в список адресов отделений банков с наивысшим курсом покупки USD.
