### ISSUE TITLE
Данные читаются однократно и не обновляются

### ISSUE THREAD

**Issue by ilyaevseev** [Pythoniser/Python_Telegram_Bot#12]
https://github.com/Pythoniser/Python_Telegram_Bot/blob/e02d7c118083bf4a7d786e95e2af50804ce53772/main.py#L3

Бот предназначен для постоянной работы.  
Поэтому данные недостаточно прочесть один раз, т.к. они устареют.  
Видимо, надо читать их каждый раз из обработчика команды в боте, пока не приделаем SQL-базу для кэширования.

**Comment by Pythoniser** [comment]
готово

**Comment by ilyaevseev** [comment]
Плохо, что в одну большую функцию свалена разная логика.

Разная логика должна быть разнесена по разным маленьким функциям.

В главной функции должно остаться только сведение разных
