### ISSUE TITLE
Отсутствует .gitignore

### ISSUE THREAD

**Issue by ilyaevseev** [Pythoniser/Python_Telegram_Bot#2]

**Comment by Pythoniser** [comment]
добавил.

**Comment by ilyaevseev** [comment]
### Во-первых:

* в закрывающем комментарии нет ссылки на соответствующий коммит: a72650bc4de32a46b0609e55fdddf4603c90d46e
* из-за этого исправление приходится вручную искать в [списке коммитов](../commits) - когда их становится много, это весьма затруднительно

### Во-вторых:

* Github сам бы добавил ссылку и закрыл issue, если бы сообщение коммита содержало бы номер issue.
* то есть так плохо:
  ```
  добавил gitignore
  ```
* а так правильно (указан номер исправляемой коммитом issue + текст понятен всем пользователям гитхаба без словаря):
  ```
  Fix #2: .gitignore added
  ```

### В третьих:

* желательно не создавать .gitignore с нуля, а добавлять строки в тот .gitignore, который создаёт PyCharm. Он большой, но там много полезного.
