### ISSUE TITLE
Раздутая start_message со смешанной логикой

### ISSUE THREAD

**Issue by ilyaevseev** [Pythoniser/Python_Telegram_Bot#3]

**Comment by Pythoniser** [comment]
Не смог таки убрать уменьшить код в структуре. В любом случае, для корректной работы запросов и перехвата ошибок с выводом соответствующего сообщения необходимо основной код помещать в декоратор @bot.message_handler(commands=['currency']) 
по сути это логично. До введения команды /currency,  request, по сути, смысла не имеет, если мы не дудосеры конечно)

**Comment by Pythoniser** [comment]
Если появятся мысли по уменьшению раздутости - реализую.
