### ISSUE TITLE
Путь к настройкам должен быть не абсолютным, а относительным.

### ISSUE THREAD

**Issue by ilyaevseev** [Pythoniser/Python_Telegram_Bot#3]
https://github.com/Pythoniser/Python_Telegram_Bot/blob/1f0927c8dd2bbadaa6f6ad52f59481a5f438b1d3/main.py#L6

Не у всех есть диск F: с папкой "Python for test".

**Comment by Pythoniser** [comment]
Сделано

**Comment by ilyaevseev** [comment]
git push сделали? по ссылке вижу старый неверный вариант.

**Comment by ilyaevseev** [comment]
Fixed by 52ccc6815fdd672d042de5f5cace1bc1f8ac951a
