### ISSUE TITLE
Мусорные комментарии лучше убрать

### ISSUE THREAD

**Issue by ilyaevseev** [Pythoniser/Python_Telegram_Bot#4]
https://github.com/Pythoniser/Python_Telegram_Bot/blob/1f0927c8dd2bbadaa6f6ad52f59481a5f438b1d3/main.py#L2

Код должен быть чистым.

Если есть проблема - лучше создайте здесь issue про неё.

**Comment by Pythoniser** [comment]
Сделано.

**Comment by ilyaevseev** [comment]
git push сделали? по ссылке вижу, что мусор никуда не делся.

В [истории коммитов](../commits) исправление не видно.

**Comment by Pythoniser** [comment]
Я открываю файл main здесь. Там все чисто.
Во всех остальных файлах тоже все исправлено еще 12 дне назад.

**Comment by ilyaevseev** [comment]
Верно, моя ошибка, ссылка смотрит на старый коммит.

Гитхаб позволяет закрывать issue автоматически, если исправляющий коммит содержит номер issue, например:

* Fix #4: remove garbage commit

Если issue закрывается вручную, в финальном комментарии надо сделать ссылку на исправивший её коммит, например:

* Fixed by 52ccc6815fdd672d042de5f5cace1bc1f8ac951a
