### ISSUE TITLE
Модуль requests используется в программе, но не указан в requirements.txt

### ISSUE THREAD

**Issue by ilyaevseev** [Pythoniser/Python_Telegram_Bot#7]
https://github.com/Pythoniser/Python_Telegram_Bot/blob/e02d7c118083bf4a7d786e95e2af50804ce53772/main.py#L1

Это означает, что инсталляция бота через "pip install -U -r requirements.txt" его не установит, поэтому при попытке запуска сразу выскочит ошибка.

**Comment by Pythoniser** [comment]
добавил.
