### ISSUE TITLE
В первой строке нужен shebang

### ISSUE THREAD

**Issue by ilyaevseev** [Pythoniser/Python_Telegram_Bot#8]
https://github.com/Pythoniser/Python_Telegram_Bot/blob/e02d7c118083bf4a7d786e95e2af50804ce53772/main.py#L1

Первой строкой в приложениях на Питоне должна быть такая:
```
#!/usr/bin/env python3
```
В крайнем случае такая:
```
#!/usr/bin/python3
```
Иначе в Линуксе возникнут проблемы с запуском.

Объяснение: https://ru.wikipedia.org/wiki/Шебанг_(Unix)

**Comment by Pythoniser** [comment]
Готово.

**Comment by ilyaevseev** [comment]
Плохо, что нет ссылки на исправивший коммит.

Если сообщение коммита содержит номер исправляемой issue, Github закроет её автоматически и поставит ссылку на коммит в закрывающий комментарий. Например:
```
Fix #8: shebang added
```
