### ISSUE TITLE
Не учитывается возможность ошибки в requests.get

### ISSUE THREAD

**Issue by ilyaevseev** [Pythoniser/Python_Telegram_Bot#9]
https://github.com/Pythoniser/Python_Telegram_Bot/blob/e02d7c118083bf4a7d786e95e2af50804ce53772/main.py#L3

Что будет, если не получится загрузить данные? Надо предусмотреть такую ситуацию:
* чтобы программа продолжила работать
* повторяла попытки загрузить данные
* сообщала пользователям об ошибке, пока загрузка не произойдёт успешно

**Comment by Pythoniser** [comment]
Готово. сделано в конструкции try:
   requests.get('http://www...)
except requests.ConnectionError:
подстановка неправильного адреса для проверки показала корректную работу. В бот выводится сообщение о недоступности сервиса и предложением попробовать позже.
